language: android
android:
    components:
        - tools

        # The BuildTools version used by your project
        - build-tools-23.0.2

          # The SDK version used to compile your project
        - android-23
